# coding: utf8

# Copyright 2014-2015 Vincent Jacques <vincent@vincent-jacques.net>

from .test_batch_delete_item import BatchDeleteItemLocalIntegTests
from .test_iterate_batch_get_item import IterateBatchGetItemLocalIntegTests
from .test_batch_put_item import BatchPutItemLocalIntegTests
from .test_iterate_list_tables import IterateListTablesLocalIntegTests
from .test_iterate_query import QueryIteratorLocalIntegTests
from .test_iterate_scan import ScanIteratorLocalIntegTests
from .test_wait_for_table_activation import WaitForTableActivationLocalIntegTests
from .test_wait_for_table_deletion import WaitForTableDeletionLocalIntegTests
